name: graduation_project_main
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  email_validator: ^3.0.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.0.6
  intl: ^0.20.2
  firebase_storage: ^12.4.4
  supabase_flutter: ^2.8.4
  typewritertext: ^3.0.9
  flutter_rounded_date_picker: ^3.0.4
  day_night_time_picker: ^1.2.0
  animated_toggle_switch: ^0.8.4
  uuid: ^3.0.7
  bottom_picker: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cards_home_player/imgs/
    - assets/home_loves_tickets_top/imgs/
    - assets/payment_successful_check/imgs/
    - assets/stadium_information_player_pg/imgs/
    - assets/welcome_signup_login/imgs/
    - assets/notifications/imgs/
    - assets/payment/imgs/
    - assets/stdowner_addNewStadium/imgs/
    - assets/editstadium_stdown/imgs/
    - assets/no_internet_connection/imgs/
    - assets/sharedBackground.png
    - assets/loading.gif
    - assets/splashBackground.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: eras-itc-bold
      fonts:
        - asset: assets/fonts/eras-itc-bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

    - family: eras-itc-light
      fonts:
        - asset: assets/fonts/ITC Eras Light Regular.otf

    - family: eras-itc-demi
      fonts:
        - asset: assets/fonts/ITC Eras Demi Regular.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
