// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3QODzqB5OcPCU9LbJ93JqQ1hEMNyYks',
    appId: '1:672497829321:web:1ff1474c1c959f137d9418',
    messagingSenderId: '672497829321',
    projectId: 'book-app-5d69f',
    authDomain: 'book-app-5d69f.firebaseapp.com',
    storageBucket: 'book-app-5d69f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVJ-OHPqGKrUfQeV1m5TKOyeWdRMM15I',
    appId: '1:672497829321:android:16b68cb90d4e64b77d9418',
    messagingSenderId: '672497829321',
    projectId: 'book-app-5d69f',
    storageBucket: 'book-app-5d69f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XwBvWGWscOxNeMFBUupz3ftpY__m7Og',
    appId: '1:672497829321:ios:aec2285cafd0db9a7d9418',
    messagingSenderId: '672497829321',
    projectId: 'book-app-5d69f',
    storageBucket: 'book-app-5d69f.firebasestorage.app',
    androidClientId: '672497829321-tuba9eibtda87pmec4sq2t2obervjufa.apps.googleusercontent.com',
    iosClientId: '672497829321-vflci4loks3ettehg9atfh9m6bsnqrlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProjectMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XwBvWGWscOxNeMFBUupz3ftpY__m7Og',
    appId: '1:672497829321:ios:aec2285cafd0db9a7d9418',
    messagingSenderId: '672497829321',
    projectId: 'book-app-5d69f',
    storageBucket: 'book-app-5d69f.firebasestorage.app',
    androidClientId: '672497829321-tuba9eibtda87pmec4sq2t2obervjufa.apps.googleusercontent.com',
    iosClientId: '672497829321-vflci4loks3ettehg9atfh9m6bsnqrlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProjectMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo3QODzqB5OcPCU9LbJ93JqQ1hEMNyYks',
    appId: '1:672497829321:web:43090000e28a48ba7d9418',
    messagingSenderId: '672497829321',
    projectId: 'book-app-5d69f',
    authDomain: 'book-app-5d69f.firebaseapp.com',
    storageBucket: 'book-app-5d69f.firebasestorage.app',
  );
}
